version: '3.8'

## bind mounts: make host machine dirs visible in container
## volumes    : persistent mounts, only inside the container
## volumes+   : put a volume on top of a bind mount (+)

services:  

  skeleton:
    build:
      context: ./skeleton
      dockerfile: docker/Dockerfile.dev
    restart: 'no'
    volumes:
      # mount (1) source code directory as docker mount:
      - ./skeleton/skeleton:/usr/src/app/skeleton # (1) the source code in ./skeleton/skeleton
      - ./skeleton/docker:/usr/src/app/docker # (2) docker entry-points in ./skeleton/docker
      - ./datashare:/usr/datashare # mount (3)
      - ./secrets:/usr/secrets # mount (4)
    # in mount(2) -> maps to ./skeleton/docker/entrypoint_dev.bash:
    entrypoint: /usr/src/app/docker/entrypoint_dev.bash 
